// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.10;

import "../../interfaces/IModule.sol";

import "../Storage.sol";

/**
 * @dev do NOT edit this file unless you know what you are doing !!
 */
abstract contract Module is CrossStorage, IModule {
    function id() public pure virtual returns (bytes32);

    function meta()
        public
        pure
        virtual
        returns (
            bytes32[] memory methodIds,
            bytes4[] memory selectors,
            bytes32[] memory initialStates
        );

    function _readState(uint256 index) internal view returns (bytes32) {
        require(index < _moduleData[id()].length, "RNG"); // out of range
        return _moduleData[id()][index];
    }

    function _writeState(uint256 index, bytes32 newVal) internal returns (bytes32) {
        require(index < _moduleData[id()].length, "RNG"); // out of range
        bytes32 oldVal = _moduleData[id()][index];
        _moduleData[id()][index] = newVal;
        return oldVal;
    }
}
